name: "Ruff"

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
  schedule:
    - cron: "33 1 * * 3"

jobs:
  ruff:
    name: "See: docs.astral.sh/ruff"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files
        run: ls -l
      - name: Download ruff
        run: ./.github/scripts/get-ruff.sh
      - name: Run ruff
        run: ./ruff check ./pyglossary ./tests/ --preview
